after-startup-command = [
	'exec-and-forget sketchybar',
	'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 100

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# (qwerty|dvorak)
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']


# set some apps to open w floating mode, so aero doesn't
# attempt to put them into the tile layout.
[[on-window-detected]]
if.app-name-regex-substring = 'lunar' # lunar client (game launcher)
run = 'layout floating'
[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'
[[on-window-detected]]
if.app-name-regex-substring = 'photo'
run = 'layout floating'
[[on-window-detected]]
if.app-name-regex-substring = 'iPhone'
run = 'layout floating'
[[on-window-detected]]
if.app-name-regex-substring = 'calendar'
run = 'layout floating'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#           5      See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        45 
outer.right =      10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

alt-ctrl-shift-f = 'fullscreen'
alt-ctrl-f = 'layout floating tiling'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -25'
alt-shift-equal = 'resize smart +25'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace .Misc-1'
alt-2 = 'workspace .Misc-2'
alt-3 = 'workspace .Misc-3'
alt-4 = 'workspace .Misc-4'
alt-5 = 'workspace .Misc-5'

alt-a = 'workspace A͙nki'
alt-s = 'workspace S͙ettings'
alt-d = 'workspace D͙iscord'
alt-f = 'workspace F͙irefox'
alt-g = 'workspace G͙ame'
alt-m = 'workspace M͙usic'
alt-o = 'workspace O͙BS'
alt-t = 'workspace T͙erminal'
alt-v = 'workspace V͙ivaldi'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace

alt-shift-1 = 'move-node-to-workspace .Misc-1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace .Misc-2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace .Misc-3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace .Misc-4 --focus-follows-window'
alt-shift-5 = 'move-node-to-workspace .Misc-5 --focus-follows-window'

alt-shift-a = 'move-node-to-workspace A͙nki --focus-follows-window'
alt-shift-s = 'move-node-to-workspace S͙ettings --focus-follows-window'
alt-shift-d = 'move-node-to-workspace D͙iscord --focus-follows-window'
alt-shift-f = 'move-node-to-workspace F͙irefox --focus-follows-window'
alt-shift-g = 'move-node-to-workspace G͙ame --focus-follows-window'
alt-shift-m = 'move-node-to-workspace M͙usic --focus-follows-window'
alt-shift-o = 'move-node-to-workspace O͙BS --focus-follows-window'
alt-shift-t = 'move-node-to-workspace T͙erminal --focus-follows-window'
alt-shift-v = 'move-node-to-workspace V͙ivaldi --focus-follows-window'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
