#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'rprompt'
  [[blocks.segments]]
     foreground = "#007ACC"
     style = "plain"
     template = " {{ .CurrentDate | date .Format }} "
     type = "time" 
     [blocks.segments.properties]
            time_format = "15:04:05"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  [[blocks.segments]]
    foreground = "#e0f8ff"
    foreground_templates = ["{{ if gt .Code 0 }}#ef5350{{ end }}"]
    style = "plain"
    template = "> "
    type = "status"
    [blocks.segments.properties]
      always_enabled = true

[transient_prompt]
  foreground = "#e0f8ff"
  foreground_templates = ["{{ if gt .Code 0 }}#ef5350{{ end }}"]
  style = "plain"
  template = "| "
  type = "status"
  background = "transparent"
