alias dotfiles="cd ~/.config/"

alias shconf="v ~/.config/zsh"
#alias ohmyzsh="v ~/.oh-my-zsh"
alias vconf="v ~/.config/nvim"
alias wezconf="v ~/.config/wezterm/wezterm.lua"
alias prompt="v ~/.config/ohmyposh/"
alias tmuxconf="v ~/.config/tmux/tmux.conf"
alias aeroconf="v ~/.config/aerospace/aerospace.toml"
alias sketchyconf="v ~/.config/sketchybar/sketchybarrc"
